

version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: hao091101
      MYSQL_DATABASE: sample_db
    ports:
      - "3306:3306"
    networks:
      - mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  mysql:
    driver: bridge
  zipkin:
    driver: bridge
