eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082
  error:
    include-message: always
spring:
  application:
    name: authservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: hao091101
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0