eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instant.hostname}:${server.port}/eureka/
server:
  port: 8082
  error:
    include-message: always
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: hao091101
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
  application:
    name: authservice